[workspace]
members = [
  "cotoami_desktop/tauri",
  "cotoami_db",
  "cotoami_node",
]
resolver = "2"

[workspace.package]
authors = ["Daisuke Morita <daisuke.marubinotto@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.75"
version = "0.1.0"
