# As of 2023/07, rust-analyzer doesn't seem to respect this file 
# unless specifying "+nightly" in the `Rustfmt: Extra Args` config.

fn_single_line = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
single_line_let_else_max_width = 100
