[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "cotoami_plugin_echo"
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
extism-pdk = "1.4.1"
