name: main

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    # https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
    - name: Install packages
      run: |
        sudo apt update
        sudo apt install libwebkit2gtk-4.0-dev \
          build-essential \
          curl \
          wget \
          libssl-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev

    - name: Run tests
      # WARN: actions-rs has been unmaintained for quite a while
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features
