name: main

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    # Install system dependencies to build a Tauri app on Linux
    # https://github.com/tauri-apps/tauri-action
    - name: Install packages
      run: |
        sudo apt update
        sudo apt-get install -y \
          libwebkit2gtk-4.1-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf

    - name: Run cotoami_node tests
      working-directory: cotoami_node
      # WARN: actions-rs has been unmaintained for quite a while
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features

    - name: Run cotoami_desktop tests
      working-directory: cotoami_desktop/tauri
      # WARN: actions-rs has been unmaintained for quite a while
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release --all-features
