name: release-desktop

on:
  push:
    branches:
    - release-desktop

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - platform: 'macos-latest' # for Arm based macs (M1 and above).
          args: '--target aarch64-apple-darwin'
        - platform: 'macos-latest' # for Intel based macs.
          args: '--target x86_64-apple-darwin'
        - platform: 'ubuntu-22.04' 
          args: ''
        - platform: 'windows-latest'
          args: ''

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2  # to detect version change in detect_version

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 23
        cache: sbt

    # https://eed3si9n.com/setup-sbt/
    - name: Install sbt
      uses: sbt/setup-sbt@v1

    - name: Detect app version
      uses: salsify/action-detect-and-tag-new-version@v2
      id: detect_version
      with:
        create-tag: false
        version-command: cd cotoami_desktop/tauri && cargo read-manifest | jq -r .version

    - name: Build and release desktop app
      if: ${{ steps.detect_version.outputs.previous-version != steps.detect_version.outputs.current-version }}
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APP_VERSION: ${{ steps.detect_version.outputs.current-version }}
      with:
        projectPath: cotoami_desktop/tauri
        appVersion: ${{ env.APP_VERSION }}
        tagName: desktop-v${{ env.APP_VERSION }}
        releaseName: Cotoami Desktop v${{ env.APP_VERSION }}
        releaseDraft: false
        prerelease: false
        includeDebug: true
        includeRelease: false

