name: release-desktop

on:
  push:
    branches:
    - release-desktop

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: 17

    - name: Detect app version
      uses: salsify/action-detect-and-tag-new-version@v2
      id: detect_version
      with:
        create-tag: false
        version-command: cd cotoami_desktop/tauri && cargo read-manifest | jq -r .version

    - name: Build and release desktop app
      if: ${{ steps.detect_version.outputs.previous-version != steps.detect_version.outputs.current-version }}
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        projectPath: cotoami_desktop/tauri
        appVersion: ${{ steps.detect_version.outputs.current-version }}
        tagName: desktop-v__VERSION__
        releaseName: Cotoami Desktop v__VERSION__
        releaseDraft: false
        prerelease: false
