name: release-desktop-linux

on:
  push:
    branches:
    - release-desktop-linux

jobs:
  # https://github.com/tauri-apps/tauri-action
  publish-tauri:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    container:
      # A relatively old system such as Ubuntu 18.04 is more suited than Ubuntu 22.04, 
      # as the binary compiled on Ubuntu 22.04 will have a higher requirement of the glibc version.
      # https://v1.tauri.app/v1/guides/building/linux
      #
      # However, Node v20 cannot be installed on 18.04 with the error: 
      # "version `GLIBC_2.28' not found". So ended up using 20.04 instead.
      image: ubuntu:20.04
    steps:
    # Tauri dependencies
    # https://tauri.app/v1/guides/getting-started/prerequisites#setting-up-linux
    # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
    # Unable to locate package libwebkit2gtk-4.1-dev on ubuntu:20.04
    #
    # git-lfs installation
    # https://github.com/git-lfs/git-lfs/wiki/Installation#docker-recipes
    - name: Install dependencies
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl ca-certificates
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | bash
        DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          git \
          git-lfs \
          unzip \
          jq \
          build-essential \
          wget \
          file \
          libssl-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.0-dev \
          libappindicator3-dev \
          librsvg2-dev \
          patchelf
        git lfs install

    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # https://github.com/actions/setup-node/issues/182
    - name: Install yarn
      run: npm install -g yarn

    - name: Install Rust stable
      uses: dtolnay/rust-toolchain@stable

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: corretto
        java-version: 23
        cache: sbt

    # https://eed3si9n.com/setup-sbt/
    - name: Install sbt
      uses: sbt/setup-sbt@v1

    - name: Detect app version
      id: detect_version
      run: |
        VERSION=$(cd cotoami_desktop/tauri && cargo read-manifest | jq -r .version)
        echo $VERSION
        echo "current-version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Build and release desktop app
      uses: tauri-apps/tauri-action@v0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        APP_VERSION: ${{ steps.detect_version.outputs.current-version }}
      with:
        projectPath: cotoami_desktop/tauri
        appVersion: ${{ env.APP_VERSION }}
        tagName: desktop-v${{ env.APP_VERSION }}
        releaseName: Cotoami Desktop v${{ env.APP_VERSION }}
        releaseDraft: false
        prerelease: false
        includeDebug: false
        includeRelease: true
